mainpro/mainapp/urls.py
from django.conf.urls import url,include
from mainapp import views

#TEMPLATE TAGGING
app_name='mainapp'

urlpatterns = [
    url(r'^reg/$',views.reg,name='reg'),
    url(r'^user_login/$',views.user_login,name='user_login'),
     ]

mainpro/mainpro/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from mainapp import views


urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^abc/',include('mainapp.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special')
]

mainpro/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.PROTECT)

    #additional
    portfolio_site = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

mainpro/mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from mainapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site',)

mainpro/mainapp/views.py
from django.shortcuts import render
from mainapp.forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'mainapp/index.html')

@login_required
def special(request):
    return render(request,'You are logged in, Nice')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def reg(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'mainapp/reg.html',
                                {'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            print("Someone tried to login and failed mesirably")
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request,'mainapp/login.html',{})

mainpro/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">



      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">DJANGO</a>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'mainapp:reg' %}">REGISTER</a>
        </li>

        {% if user.is_authenticated %}
        <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>

        {% else %}
        <li><a class="nav-link" href="{% url 'mainapp:user_login' %}">Login</a></li>

        {% endif %}

      </ul>

    </nav>
    {% block body_block %}
    {% endblock %}
  </body>
</html>

mainpro/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block body_block %}

<h1>WELCOME</h1>

{% endblock %}

mainpro/templates/mainapp/login.html
{% extends 'mainapp/base.html' %}
{% block body_block %}

<h1>Please Login</h1>
<form action="{% url 'mainapp:user_login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input  type="text" name="username" placeholder="Enter Username">
<br>
  <label for="password">Password:</label>
  <input  type="password" name="password">
 <br>
  <input type="submit" name="" value="Login">

</form>

{% endblock %}

mainpro/templates/mainapp/reg.html
{% extends 'mainapp/base.html' %}
{% block body_block %}

  {% if registered %}
    <h1>Thankyou for registering!</h1>
  {% else %}
     <h1>Register Here!</h1>
     <h3>Fill out the form</h3>
          <form method="post">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit" value="Register">
          </form>

  {% endif %}

{% endblock %}